openapi: 3.0.3
info:
  title: FSM
  description: The Truth Is Out There
  version: 0.0.1
servers:
  - url: http://localhost/v1
    description: Development server
paths:
  /states/{entityId}:
    parameters:
      - in: path
        name: entityId
        schema:
          type: integer
          format: int32
    post:
      operationId: changeState
      summary: Changes entity state
      description: Changes entity state #fixme: Add description for transitions and possible race conditions
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string